
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.port: 2018
spring:
  datasource:
    url: jdbc:mysql://localhost/healthc
    username: root
    password: Guna@1996

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform=org:
      hibernate:
        dialect: MySQL8InnoDBDialect

